name: attendo

services:
  # Backend API service
  backend:
    build:
      context: ../back/src
      dockerfile: Dockerfile
    container_name: attendo-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - attendo-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: attendo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - attendo-network
    restart: unless-stopped

networks:
  attendo-network:
    driver: bridge
