name: attendo

services:
  # Database service
  database:
    image: postgres:15
    container_name: attendo-database
    environment:
      - POSTGRES_DB=atendo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=miarel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atendo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API service
  backend:
    build:
      context: ../back
      dockerfile: Dockerfile
    container_name: attendo-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Host=database;Port=5432;Database=atendo_db;Username=postgres;Password=miarel
    depends_on:
      database:
        condition: service_healthy
    networks:
      - attendo-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: attendo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - attendo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  attendo-network:
    driver: bridge
