name: attendo

services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.0
    container_name: attendo-traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - attendo-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: ../back/src
      dockerfile: Dockerfile
    container_name: attendo-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`yourdomain.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.docker.network=attendo_attendo-network"
    networks:
      - attendo-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: attendo-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=attendo_attendo-network"
    depends_on:
      - backend
    networks:
      - attendo-network
    restart: unless-stopped

networks:
  attendo-network:
    driver: bridge
