name: Test Local Workflow

on:
  workflow_dispatch:

jobs:
  test-local:
    name: Test Local
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Test Frontend
        run: |
          cd front
          npm ci
          npm run lint
          npx tsc --noEmit
          npm run build

      - name: Test Backend
        run: |
          cd back
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --configuration Release --no-build --verbosity normal

      - name: Test Docker
        run: |
          docker build -t test-frontend ./front
          docker build -t test-backend ./back
